buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.11.0'
    }
}

ext {
    minSdkVersion = 26
    targetSdkVersion = 34
    compileSdkVersion = 34
    ndkVersion = '27.0.12077973'
}

allprojects { project ->
    repositories {
        google()
        mavenCentral()
    }
}
